print("|==================================================|")
print("|GEOMETRIA ANALÍTICA 02 DISTÂNCIA ENTRE DOIS PONTOS|")
print("|==================================================|")
x1 = (int(input("          Digite o valor do X1: ")))
x2 = (int(input("          Digite o valor do X2: ")))
y1 = (int(input("          Digite o valor do Y1: ")))
y2 = (int(input("          Digite o valor do Y2: ")))
a_b = ((x1-x2)**2) + ((y1-y2)**2)
print("================================================")
print("           RESULTADO: Raíz de",a_b,"            ")
print("================================================")
