import math
print("====================================")
print("EXERCÍCIO (A)")
print("Expressão Quadrática")
print("")
x = int(input("Digite um valor para 'X': "))
y = int(input("Digite um valor para 'Y': "))
r = (3* x**3 * y**2) - (5* x * y**2)
print("Resposta: ",r)
print("====================================")
print("")
print("EXERCÍCIO (B)")
print("Cálculo de BASKARAS")
print("")
a = int(input("Dê o valor de A: "))
b = int(input("Dê o valor de B: "))
c = int(input("Dê o valor de C: "))
R2 = (b**2) - (4*a*c)
R2 = math.sqrt(R2)
x1 = -(b) + (R2)
x1 = x1 / (2*a)
x2 = -(b) - (R2)
x2 = x2 / (2*a)
print("X1: ",x1)
print("X2: ",x2)
print("=============================================================================")
print("")
print("EXERCÍCIO (C)")
c = int(input("Conversor de CELSIUS para FAHRENHEIT. Digite o valor em CELSIUS: "))
f = (c * (9/5)) + 32
print("Valor convertido em FAHRENHEIT: ",f)
print("=============================================================================")
print("")
print("EXERCÍCIO (D)")
print("Conversor de IDADE p/ DIAS/HORAS/MINUTOS e SEGUNDOS ")
i = float(input("Qual idade deseja converter?: "))
d = i*365
h = d*24
m = h*60
s = m*60
print(i,"anos, = ",d," Dias")
print(i,"anos, = ",h," Horas")
print(i,"anos, = ",m," Minutos")
print(i,"anos, = ",s," Segundos")
print("=============================================================================")
print("")
a = input("Nome completo do Aluno: ")
n1 = float(input("Nota AC 1: "))
n2 = float(input("Nota AC 2: "))
n3 = float(input("Nota AC 3: "))
n4 = float(input("Nota AC 4: "))
n5 = float(input("Nota AC 5: "))
n6 = float(input("Nota AC 6: "))
n7 = float(input("Nota AC 7 :"))
m = (n1+n2+n3+n4+n5+n6+n7) / 7
print("Aluno: ",a)
print("Média/Nota: ",m)
print("=============================================================================")
print("")

